export const actions = { 
    DELETE_DIALOG_RESPPONSE : 'DELETE_DIALOG_RESPPONSE',

    RESPOND_DECISION_DIALOG: 'RESPOND_DECISION_DIALOG',

    CUSTOMISED_MODAL_RESPONSE:"CUSTOMISED_MODAL_RESPONSE",

    SHOW_HIDE_MODAL: 'SHOW_HIDE_MODAL',
    RESPOND_MODAL: 'RESPOND_MODAL',
    SHOW_HIDE_ADD_FOLDER_MODAL:"SHOW_HIDE_ADD_FOLDER_MODAL",
    SHOW_HIDE_ADD_FILE_MODAL:"SHOW_HIDE_ADD_FILE_MODAL",
}