export const actions = {
    LOGIN_USER: "LOGIN_USER",
    REGISTER_USER: "REGISTER_USER",
    LOG_OUT_USER: "LOG_OUT_USER",
    GENERATE_PASSWORD_RESET_LINK: "GENERATE_PASSWORD_RESET_LINK",
    RESET_PASSWORD: "RESET_PASSWORD",    
}