export const actions = {
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    LOG_OUT_USER: "LOG_OUT_USER",
    GENERATE_PASSWORD_RESET_LINK_SUCCESS: "GENERATE_PASSWORD_RESET_LINK_SUCCESS",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    
}