export const actions = {
    FETCH_DOCUMENTATION_PRODUCTS : "FETCH_DOCUMENTATION_PRODUCTS",
    FETCH_DOCUMENTATION_LIST:"FETCH_DOCUMENTATION_LIST",
    FETCH_SINGLE_DOCUMENTATION:"FETCH_SINGLE_DOCUMENTATION",
    GET_FEATURES:"GET_FEATURES",
    FETCH_EXPORTED_DOCUMENTATION:"FETCH_EXPORTED_DOCUMENTATION",
    }