export const actions = {
FETCH_PRODUCTS : "FETCH_PRODUCTS",
FETCH_SINGLE_PRODUCT : "FETCH_SINGLE_PRODUCT",
FETCH_USER_PRODUCTS : "FETCH_USER_PRODUCTS",
FETCH_SINGLE_USER_PRODUCT : "FETCH_SINGLE_USER_PRODUCT",
FETCH_CLIENT_USERS:"FETCH_CLIENT_USERS",

}